### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/gidle-notify#1]
## Support

- [ ] Tier 1 support:
  - [ ] Linux / Wayland / GNOME Idle Monitor (lib-gnome-desktop)
  - [ ] Linux / Wayland / KDE/wlroots ext-idle-notify-v1 (libwayland-client)
- [ ] Tier 2 support:
  - [ ] Linux / Wayland / GNOME Idle Monitor (Gio + DBus)
  - [ ] Linux / Xorg / XScreenSaver
- [ ] Tier 3 support:
  - [ ] Windows
  - [ ] macOS

## API Draft

```
class IdleMonitor:
  constructors:
    new(GtkWindow* window, guint min_timeout);

  properties:
    gboolean idle;
    guint    min_timeout;

  methods:
    gboolean is_idle();
    guint    get_min_timeout();
    void     set_min_timeout(guint min_timeout);
```

gotk4 usage:

```go
idler := idlemonitor.NewIdleMonitor()
idler.NotifyProperty("idle", func() {
  if idler.IsIdle() {
    log.Println("user is idle")
  } else {
    log.Println("user is no longer idle")
  }
})
```
## References

- https://github.com/bkbilly/dbus_idle/blob/master/dbus_idle/__init__.py (DBus + XScreenSaver)
- https://wayland.app/protocols/ext-idle-notify-v1
- https://gitlab.gnome.org/GNOME/gnome-desktop/-/blob/master/libgnome-desktop/gnome-idle-monitor.h
